# Generated by Django 6.0 on 2025-12-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_movie_poster_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='friends',
            field=models.ManyToManyField(blank=True, to='cinema.appuser'),
        ),
    ]
