# Generated by Django 6.0 on 2025-12-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_movie_description_movie_tmdb_id_movie_trailer_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
