# Generated by Django 6.0 on 2025-12-28 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0007_alter_movie_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='salon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.salon'),
        ),
    ]
