# Generated by Django 6.0 on 2025-12-29 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0008_alter_showtime_salon'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Bekliyor'), ('Accepted', 'Kabul Edildi'), ('Rejected', 'Reddedildi')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='salon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cinema.salon'),
            preserve_default=False,
        ),
    ]
